"""add story.last_seen_at

Revision ID: 2d086a94452b
Revises: 73d7a4ca0e7b
Create Date: 2026-05-27 18:06:24.052521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d086a94452b'
down_revision = '73d7a4ca0e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('seen_at', sa.DateTime()))
    op.create_index('stories_seen_at', 'stories', ['seen_at'], unique=False)
    # ### end Alembic commands ###
    # Handmade: Attach existing stories to most recent successful fetch
    # so they can be found/updated if the next fetch hash is identical.
    # (an alternative would be to NULL out last_fetch_hash in the feeds table
    op.execute("""
        UPDATE stories
        SET seen_at = feeds.last_fetch_success
        FROM feeds
        WHERE stories.feed_id = feeds.id;
        """)
    # force re-parse of all feed documents to freshen
    # seen_at on all stories that currently exist.
    op.execute("UPDATE feeds SET last_fetch_hash = NULL;")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('stories_seen_at', table_name='stories')
    op.drop_column('stories', 'seen_at')
    # ### end Alembic commands ###
