"""add story_ref table

Revision ID: a6b7fce60801
Revises: 73d7a4ca0e7b
Create Date: 2026-06-20 00:11:29.056092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b7fce60801'
down_revision = '73d7a4ca0e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_refs',
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('feed_id', sa.BigInteger(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('story_id', 'feed_id')
    )
    op.create_index('story_refs_feed_id', 'story_refs', ['feed_id'], unique=False)
    op.create_index('story_refs_seen_at', 'story_refs', ['seen_at'], unique=False)
    # ### end Alembic commands ###

    # ### begin phil generated commands ###

    # populate story_refs from stories table
    op.execute("""
        INSERT INTO story_refs (story_id, feed_id, seen_at)
        SELECT id, feed_id, fetched_at
        FROM stories;
        """)
    # force processing of all feed documents to populate refs:
    op.execute("UPDATE feeds SET last_fetch_hash = NULL;")

    # to populate story_refs??


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('story_refs_seen_at', table_name='story_refs')
    op.drop_table('story_refs')
    # ### end Alembic commands ###
