{
 "title": "rss-fetcher alerts",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "feeds added to queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "movingAverage(stats.counters.mc.prod.rss-fetcher.queue_feeds.queued_feeds.count, '5min')"
    }
   ]
  },
  {
   "title": "rss stories output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.counters.mc.prod.rss-fetcher.gen_rss.stories.status_added.count"
    }
   ]
  },
  {
   "title": "feeds fetched",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "movingAverage(stats.timers.mc.prod.rss-fetcher.worker.total.status_SUCC.count, '5min')"
    }
   ]
  },
  {
   "title": "stories processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "movingAverage(sumSeries(stats.counters.mc.prod.rss-fetcher.worker.stories.*.count), '5min')"
    }
   ]
  }
 ]
}